#!/bin/bash

## Generating key files if not exists
KEYPATH_RSA=$OPENSHIFT_DATA_DIR/.ssh/gitkey_deployment_rsa
if [ $KEYPATH_RSA !-f ]; then
	echo "Generate key pair for wrapper to $KEYPATH_RSA"
	ssh-keygen -t rsa -N "" -C "deplyment key" -f $KEYPATH_RSA
else
	echo "Deployment key $KEYPATH_RSA already exists"
fi



## Make all binaries available in bin dir
# gems





echo "Exporting path on pre-start"
PATH=$PATH:/qweqweqweqweqwe
export PATH=$PATH

