#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

export GIT_SSH=$OPENSHIFT_REPO_DIR/misc/gitssh_wrapper.sh
echo "Env variable GIT_SSH exported as $GIT_SSH"

echo "Current user is "
echo `whoami`

nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_DIY_DIR/logs/server.log 2>&1 &
