#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

echo "Current user is "
echo `whoami`

KEYPATH_RSA=$OPENSHIFT_DATA_DIR/gitkey_deployment_rsa
if [ !-f ]; then
	echo "Generate key pair for wrapper to $KEYPATH_RSA"
	ssh-keygen -t rsa -N "" -C "deplyment key" -f $KEYPATH_RSA
else
	echo "Deployment key $KEYPATH_RSA already exists"
fi

echo "export GIT_SSH=$OPENSHIFT_REPO_DIR/misc/gitssh_wrapper.sh" > $OPENSHIFT_DATA_DIR/.bashrc
echo "Env variable GIT_SSH exported as $GIT_SSH"


nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_DIY_DIR/logs/server.log 2>&1 &
