#!/bin/bash
# 
# Syncronizes data from source directories with generic bin directory
#
#
#OPENSHIFT_DATA_DIR=/ded/www2/jenkinsagent
BINARY_DIR=$OPENSHIFT_DATA_DIR/bin
BINARY_SOURCES="$OPENSHIFT_REPO_DIR/bin $OPENSHIFT_DATA_DIR/gems/bin"

# remove corrupted links
echo "Remove broken links ..."
files=`find $BINARY_DIR -maxdepth 1 -type l`

for file in $files; do
	if [ ! -f `readlink $file` ]; then
		echo "> remove broken link $file"
		unlink $file
	fi
done

# apply links from other dirs
echo "Sync binary sources with $BINARY_DIR ..."
for source_dir in $BINARY_SOURCES; do
	if [ ! -d $source_dir ]; then
		continue;
	fi

	# find executables in source dir
	files=`find $source_dir -maxdepth 1 -perm +x`
	for filename in $files; do
		linkname=$BINARY_DIR/`basename $filename`
		echo "> create link $filename --> $linkname"
		ln -sf $filename $linkname && chmod +x $linkname
	done;
done;